heroku_django/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from django.conf import settings
from trackings.api import TrackingResource, PhotoResource

from tastypie.api import Api

v1_api = Api(api_name='v1')
v1_api.register(TrackingResource())
v1_api.register(PhotoResource())

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'heroku_django.views.index', name='index'),
    url(r'^login/$', 'heroku_django.views.login_view', name='login'),
    url(r'^logout/$', 'heroku_django.views.logout_view', name='logout'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^about/$', 'heroku_django.views.about', name='about'),
    url(r'^trackings/', include('trackings.urls', namespace='tracking')),
    # api
    url(r'^api/', include(v1_api.urls)),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

trackings/urls.py
from django.conf.urls import patterns, url
from django.conf import settings

import logging

logger = logging.getLogger('mode.debug')

urlpatterns = patterns('trackings.views',
        url(r'^$', 'index', name='index'),
        url(r'^new/$', 'new'),
        #url(r'^(?P<tracking_id>\d+)/fix/$', 'fix', name='fix'),
        url(r'^(?P<tracking_id>\d+)/$', 'show', name='show'),
        # backbone
        url(r'^backbone/$', 'backbone', name='backbone')
)

urlpatterns += patterns('', 
        url(r'^photos/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.PHOTO_ROOT}),
)

trackings/models.py
from django.core.mail import EmailMessage
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime
from django.db import models
from django.forms import ModelForm
from celery import task
from django.utils.translation import ugettext_lazy as _

import sys
import logging
logger = logging.getLogger('mode.debug')

email_message = """
<html>
<head>
<title> Maintain-e-nator </title>
</head>
<body background="https://a1.muscache.com/locations/uploads/city/hero/22/0_2831_95_1567_hero_USA_Manhattan_Skyline_061_EO.jpg">
<pre>
Hi {submitter},

    We've fixed the problem submitted by you on <strong>{pub_date}</strong> in <em>{location}</em> now.

    Thank you for your support!

Best,
-Maintain-e-nator.
</pre>
</body>
</html>
"""

class Tracking(models.Model):
    SEVERITY_LEVELS = (
            (1, 'Very severe'),
            (2, 'Severe'),
            (3, 'Fair'),
            (4, 'Can wait'),
            (5, 'Just kidding'))

    description = models.CharField(_("Issue's short description"), max_length=100)
    # Suppose to be used by maintainers.
    severity = models.IntegerField(choices=SEVERITY_LEVELS, default=3)
    latitude = models.DecimalField(max_digits=13, decimal_places=10, null=True, blank=True)
    longitude = models.DecimalField(max_digits=13, decimal_places=10, null=True, blank=True)
    building = models.CharField(max_length=20, blank=True)
    floor = models.CharField(blank=True, max_length=10)
    room = models.CharField(blank=True, max_length=10)
    location = models.CharField(blank=True, max_length=100)
    fixed = models.BooleanField(default=False)
    #TODO remove indoor field
    indoor = models.BooleanField(default=False)
    # If set `blank=True`, Django will store the empty string for CharField in db.
    submitter = models.CharField(max_length=20, blank=True)
    sub_email = models.EmailField(_('Submitter Email'), blank=True)
    pub_date = models.DateTimeField(default=datetime.datetime.now)

    def __unicode__(self):
        return u'%s : %s' % (self.description, self.location)

    @staticmethod
    def autocomplete_search_fields():
        pass

class Photo(models.Model):
    PHOTO_DIR = 'trackings/photos/'
    tracking = models.ForeignKey(Tracking)
    photo = models.ImageField(upload_to=PHOTO_DIR)

    def __unicode__(self):
        return u'%s' % self.photo.name

class Audio(models.Model):
    AUDIO_DIR = 'trackings/audios/'
    tracking = models.ForeignKey(Tracking)
    audio = models.FileField(upload_to=AUDIO_DIR)

    def __unicode__(self):
        return u'%s' % self.audio.name

# `POST form` for Tracking and Photo.
class TrackingForm(ModelForm):
    class Meta:
        model = Tracking

class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = ('photo',)

# Celery task to send thanks email once an issue is fixed.
@task(ignore_result=True)
def send_thanks_email(updated_instance_pk):
    try:
        logger.debug('Updating tracking: ' + str(updated_instance_pk))
        tracking = Tracking.objects.get(pk=updated_instance_pk)
        if tracking.fixed and tracking.sub_email:
            subject = "We've fixed the issue!"
            message = email_message.format(submitter = tracking.submitter, pub_date = tracking.pub_date.strftime('%Y-%m-%d'), location = (tracking.location or tracking.building))
            email = EmailMessage(subject, message, 'Maintain-e-nator <forkloop.dev@gmail.com>', [tracking.sub_email])
            email.content_subtype = 'html'
            email.send()
            #send_mail(subject, message, 'maintain-e-nator', [tracking.sub_email])
    except:
        logger.error(sys.exc_info()[0])

@receiver(post_save, sender=Tracking)
def send_thanks_email_wrapper(sender, **kwargs):
    """
    **kwargs:
        instance              The instance of model be saved.
        created               Whether this instance was created.
        updated_fields        Which fields are updated, only when specify explicitly in `save()`.
    """
    try:
        updated_instance_pk = kwargs.get('instance').pk
        send_thanks_email.delay(updated_instance_pk)
    except:
        logger.error(sys.exc_info()[0])

trackings/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import Http404
from django.conf import settings
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.shortcuts import render_to_response
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
#from django.views.decorators.cache import cache_page

from trackings.models import Tracking, TrackingForm, PhotoForm

import logging
logger = logging.getLogger('mode.debug')

# decorator to redirect to index page.
# used for `deprecate` views.
def render_homepage(func):
    def rendered_func(*args, **kwargs):
        return redirect('index')
        #raise Http404
    return rendered_func

def index(request):
    trackings_list = Tracking.objects.all()
    paginator = Paginator(trackings_list, 20)

    page = request.GET.get('page')
    logger.debug('Requesting page: ' + str(page))
    try:
        trackings = paginator.page(page)
    except PageNotAnInteger:
        trackings = paginator.page(1)
    except EmptyPage:
        trackings = paginator.page(paginator.num_pages)
    return render_to_response('tracking_index.html', {'trackings': trackings})

@render_homepage
def new(request):
    c = {}
    if request.method == 'POST':
        tracking_form = TrackingForm(request.POST)
        if tracking_form.is_valid():
            tracking = tracking_form.save()
            # At most 3 photos
            for i in xrange(len(request.FILES)):
                if i == 0:
                    tracking.photo_set.create(photo=request.FILES['photo'])
                else:
                    tracking.photo_set.create(photo=request.FILES['extra_photo' + str(i)])
            logger.debug('Created tracking: ' + str(tracking.pk))
            return HttpResponseRedirect(reverse('tracking:show', args=[tracking.pk]))
    else:
        tracking_form = TrackingForm()
        c.update(csrf(request))
    c['tracking_form'] = tracking_form
    photo_form = PhotoForm()
    c['photo_form'] = photo_form
    return render(request, 'trackings_new.html', c)

# @cache_page(60*10)
def show(request, tracking_id):
    try:
        tracking = Tracking.objects.get(pk=tracking_id)
    except Tracking.DoesNotExist:
        raise Http404
    # tracking = get_object_or_404(Tracking, pk=tracking_id)
    return render(request, 'trackings_show.html', {'tracking': tracking})

def backbone(request):
    return render(request, 'trackings_bb.html', {'base_url': settings.BASE_URL})

# TODO add decorator to disable it
# Ajax request to change tracking `fixed` value.
def fix(request, tracking_id):
    if request.is_ajax() and request.method == 'POST':
        try:
            tracking = Tracking.objects.get(pk=tracking_id)
        except Tracking.DoesNotExist:
            raise Http404
        update_status = request.POST['fixed']
        old_status = str(tracking.fixed).lower()
        if update_status != old_status:
            if update_status == 'true':
                message = 'true'
                tracking.fixed = True
            else: 
                message = 'false'
                tracking.fixed = False
            tracking.save()
        else:
            message = 'unchanged'
        return HttpResponse(message)
    else:
        raise Http404

trackings/templates/tracking_index.html
{% extends "trackings_basic.html" %}

{% block title %} All trackings {% endblock %}

{% block container %}
<h1>Public Posts</h1>
<div id="tracking-list">
    {% if trackings %}
    <ul>
        {% for tracking in trackings %}
        <li><a href="{% url tracking:show tracking.id %}"><em>{{ tracking.description }}</em>, {{ tracking.location }}</a></li>
        {% endfor %}
    </ul>
    <div class="pagination">
        <span class="step-links">
            {% if trackings.has_previous %}
            <a href="?page={{ trackings.previous_page_number}}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ trackings.number }} of {{ trackings.paginator.num_pages }} .
            </span>

            {% if trackings.has_next %}
            <a href="?page={{ trackings.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
    {% else %}
    <p> No trackings yet.</p>
    {% endif %}
</div>
{% endblock %}

trackings/templates/trackings_basic.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Base URL -->
        {% block base_url %}{% endblock %}
        <title>{% block title %} Maintain-e-nator {% endblock %}</title>
        <!-- Bootstrap -->
        <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "css/bootstrap-responsive.min.css" %}" rel="stylesheet">
        <link href="{% static "css/custom.css" %}" rel="stylesheet">
        {% block extra_css %}
        {% endblock %}
        {% block mustache_template %}
        {% endblock %}
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="{% url index %}">Maintain-e-nator</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li><a href="{% url admin:index %}">Admin</a></li>
                            <li><a href="{% url tracking:index %}">Trackings</a></li>
                            <li><a href="{% url about %}">About</a></li>
                            <li><a href="{% url tracking:backbone %}">Backbone</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            {% block container %}{% endblock %}
        </div>
        {% block footer %}
        {% endblock %}
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        <script src="{% static "js/jquery.cookie.js" %}"></script>
        {% block extra_scripts %}{% endblock %}
    </body>
</html>

trackings/templates/trackings_bb.html
{% extends "trackings_basic.html" %}
{% load staticfiles %}

{% block title %}
{{ block.super }} | Backbone
{% endblock %}

{% block base_url %}
<base href="{{ base_url }}" />
{% endblock %}

{% block extra_css %}
<link href="{% static "css/backbone.css" %}" rel="stylesheet" />
{% endblock %}

{% block mustache_template %}
<script id="tracking-list-template" type="text/x-mustache-template">
    <p><% description %></P>
    <p class="location-info"><% location %></p>
    <div>
        <% #photos %>
        <img class="list-view-image" src="<% photo %>" />
        <% /photos %>
    </div>
    <div class="submitter-info">
        <div>
            <img class="avatar" src="http://www.gravatar.com/avatar/<% sub_email %>?s=40" />
        </div>
        <p>Submitted by <strong><% submitter %><% ^submitter %>Anonymous<% /submitter %></strong> on <em><% pub_date %></em> </p>
    </div>
</script>
<script id="tracking-detail-template" type="text/x-mustache-template">
    <a id="all-trackings-btn" href="#"> All Trackings </a>
    <h1> <% description %> </h1>
    <h2> <span class="location-marker"></span><% location %> </h2>
    <div id="tracking-detail-wrap">
        <div id="tracking-detail-image">
            <% #photos %>
                <img class="detail-view-image" src="<% photo %>" />
            <% /photos %>
        </div>
        <div id="tracking-detail-map">
            <div id="map-canvas" class="map">
        </div>
</script>
<script id="base-url" type="text/x-mustache-template">
{{ base_url }}
</script>
{% endblock %}

{% block container %}
<div id="tracking-app">
    <h1> Trackings </h1>
    <div id="all-trackings">
    </div>
</div>
{% endblock %}

{% block extra_scripts %}
<script src="http://maps.google.com/maps/api/js?key=AIzaSyCL6FCIh_lcj9RPY-TZ6O08acGrffJvbq8&sensor=false"></script>
<script src="{% static "js/jquery.masonry.min.js" %}"></script>
<script src="{% static "js/underscore-min.js" %}"></script>
<script src="{% static "js/backbone-min.js" %}"></script>
<script src="{% static "js/mustache.js" %}"></script>
<script src="{% static "js/app.js" %}"></script>
{% endblock %}

trackings/templates/trackings_new.html
{% extends "trackings_basic.html" %}

{% block title %} New tracking {% endblock %}

{% block container %}
<h1> New Tracking </h1>
<div class="hero-unit">
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form enctype="multipart/form-data" action="/trackings/new/" method="post">
    {% csrf_token %}
    {{ tracking_form.as_p }}
    {{ photo_form.as_p }}
    <input class="btn" id="add_photo" type="button" value="Add another photo" />
    <input class="btn" type="submit" value="Submit" />
</form>
</div>
{% endblock %}

trackings/templates/trackings_show.html
{% extends "trackings_basic.html" %}
{% block title %} Tracking {{ tracking.id }} {% endblock %}

{% load staticfiles %}
{% block container %}
<div class="report-wrap">
    {% comment %}
    {% if user.is_authenticated %}
    <div class="report-edit">
        <form action="{% url tracking:fix tracking.id %}" method="post" id="fixForm">
            {% csrf_token %}
            {% if tracking.fixed %}
                <input type="checkbox" name="fixed" checked="checked">
            {% else %}
                <input type="checkbox" name="fixed">
            {% endif %}
            Mark it as fixed, yup!
            <input type="submit" value="Save" class="btn">
        </form>
    </div>
    {% endif %}
    {% endcomment %}
    <div class="report">
        <div class="report-inner">
        <h2>{{ tracking.description }}</h2>
        {% if tracking.fixed %}
            <span>&#10003</span>
        {% else %}
            <span>&#10007</span>
        {% endif %}
        <div class="report-audio">
            {% for audio in tracking.audio_set.all %}
                <audio controls="controls">
                    <source src="{% static audio.audio.name %}" type="audio/wav">
                </audio>
            {% endfor %}
        </div>
        <div class="report-location">
            <p><span>{{ tracking.location }}</span></p>
        </div>
        {% for photo in tracking.photo_set.all %}
        <img src="{% static photo.photo.name %}" />
        {% endfor %}
    </div>
    </div>
    <div id="report-map">
        <div id="map-canvas" class="map">
        </div>
    </div>
    <div class="report-foot">
        <p>
            <a href="{% url tracking:index %}"> All trackings </a>
        </p>
    </div>
    </div>
{% endblock %}
{% block extra_scripts %}
<script src="http://maps.google.com/maps/api/js?key=AIzaSyCL6FCIh_lcj9RPY-TZ6O08acGrffJvbq8&sensor=false"></script>
<script src="{% static "js/loadmap.js" %}"></script>
{% endblock %}